### ISSUE TITLE
Does not appear to work with latest Unleashed 12

### ISSUE THREAD

**Issue by ALD53105** [Mywk/FlipperTemperatureSensor#2] opened 2022-10-31 01:18 UTC
Currently running Unleashed 12 and the app launches but does not find the sensor. I have double and triple checked my wiring and always get "Sensor not found".

**Comment by Mywk** [comment] 2022-10-31 01:25
I haven't had the chance to update to the latest version but let's go through some basic troubleshooting first:

1-  Are the four connectors correctly soldered?

2- Are the SCL and SDA connections correct? Re-check the diagram if necessary.

3- On the sensor board, there should be three contacts in the center, for it to work correctly they must be soldered together (basically drop a blob of solder to connect the three of them). Without the solder it looks like this:
![image](https://user-images.githubusercontent.com/5620014/198913015-b768de94-1b3c-4639-b7f8-a2837e867b40.png)

**Comment by oldbug62** [comment] 2022-11-08 17:54
@ALD53105 Have you fixed the problem?

**Comment by ALD53105** [comment] 2022-11-08 23:02
Thank you for your reply. I ordered the sensor from Amazon and the contacts were not soldered. I have not had a chance to solder them yet, but I appreciate the information and I'm sure that's what the issue is.

**Comment by oldbug62** [comment] 2022-11-09 15:25
I ordered from aliexpress and it wasn't soldered either. I think its not necessary. I connect the 3 pins an it doesent work. I have UL 14.

**Comment by Mywk** [comment] 2022-11-09 15:36
In some of the boards the pull up resistors are not connected by default.
Usually, if you're hooking up multiple I2C devices on the same bus, you want to disable these resistors, I think the only reason they ship the boards like that is for cost savings.

In this case you will want to have them all connected otherwise the app will not recognize the connection.

@oldbug62 I couldn't find any reference to a UL14 sensor, if it's a clone it should work as long as it uses I2C.

**Comment by oldbug62** [comment] 2022-11-09 17:18
@Mywk Thanks for the Infos, i have connected the resistors and ist working with Unleashed 14.

The Humidity seems to low (41,49%) i have some other Weatherstations an the all show about 65-68 %
The Temp is OK

**Comment by Mywk** [comment] 2022-11-10 12:47
That's great!

Regarding the humidity I don't have a second sensor here right now to make a comparison but I'll add it to my to-do list and if the problem is in the code I'll make sure to fix it.

Closing as the issue has also been solved.

**Closed as completed by Mywk** 2022-11-10 12:47 UTC
